name: Update Release Configs

# Generates release-please config files from release-channels.yml

on:
  workflow_dispatch:

jobs:
  update-configs:
    uses: heroku/npm-release-workflows/.github/workflows/update-release-configs.yml@main
    with:
      runs_on: sfdc-hk-ubuntu-latest  # Options: ubuntu-latest | sfdc-hk-ubuntu-latest | pub-hk-ubuntu-24.04-ip
    permissions:
      contents: write
      pull-requests: write
